# Generated by Django 4.2.24 on 2025-09-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='title',
            new_name='job_title',
        ),
    ]
