# Generated by Django 4.2.24 on 2025-09-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
                ('avatar', models.ImageField(blank=True, upload_to='uploads/')),
                ('ordinal', models.IntegerField(default=0)),
            ],
        ),
    ]
